// export const baseUrl = "http://itsolution24x7.com/request_form/";
// export const register_API = `${baseUrl}/api/v1/register`;

// export const baseUrl = "http://94.23.24.69/brainwashapp/api/v1/";
// export const baseUrl = 'http://brain.masology.net/api/v1/';
export const baseUrl = 'http://94.23.24.69/brainwash/api/v1/';
export const order_request = `${baseUrl}orders`;
export const Get_order = `${baseUrl}findorders`;
export const Accept_order = `${baseUrl}jobs`;
export const Accepted_order = `${baseUrl}acceptedJob`;
export const login_Api = `${baseUrl}login`;
export const register_Api = `${baseUrl}register`;
export const Editprofile_Api = `${baseUrl}userupdate`;
export const Laundrystatus_Api = `${baseUrl}register`;
export const Washhistory_Api = `${baseUrl}orders`;
export const UpdateOrder_Api = `${baseUrl}orders`;
export const forget_password = `${baseUrl}forget-password?email=`;
export const verify_reset_code = `${baseUrl}verify-reset-code?verification_code=`;
export const reset_password = `${baseUrl}reset-password`;
export const get_universities = `${baseUrl}universities`;
export const Transaction = `${baseUrl}transactions`;
export const verify_otp = `${baseUrl}code`;
export const Resend_Otp = `${baseUrl}resend-code`;
export const role_Api = `${baseUrl}routing`;
export const get_user = `${baseUrl}users`;
export const get_Scholarships = `${baseUrl}scholarships`;
export const Cancel_order = `${baseUrl}cancelled-orders`;
export const Wallet = `${baseUrl}wallets`;
export const pages = `${baseUrl}pages`;
export const Report = `${baseUrl}reports`;
export const Checkcancel = `${baseUrl}checkJob`;
export const logout = `${baseUrl}logout`;
